### ISSUE TITLE
`/api/query/exp` support

### ISSUE THREAD

**Issue by ace-han** [turn/splicer#5] opened 2016-09-18 08:30 UTC
Hi, guys

So, I gave `splicer` a try today. However, I found out that it didn't support expression queries which come from `opentsdb-2.3`.

The system we have already built is heavily based on this api ( `/api/query/exp` ) for flexibility and complicated cases

I'm writing this as a feature request, please kindly help, thx.

**Comment by johann8384** [comment] 2016-10-08 14:40
Duplicate of #1

**Closed as completed by johann8384** 2016-10-08 14:40 UTC
Labels: duplicate
